### ISSUE TITLE
%i記法でコード量を削減する

### ISSUE THREAD

**Issue by norotime** [yuforest/property-exem#5]
https://github.com/yuforest/property-exem/blob/35042bb39aada7cd28a5075dae1e648eeea514fc/app/controllers/nearest_stations_controller.rb#L2

**Comment by norotime** [comment]
before
```
 before_action :set_nearest_station, only: [:show, :edit, :update, :destroy] 
```

after
```
 before_action :set_nearest_station, only: %i[show edit update destroy] 
```

**Comment by norotime** [comment]
@yuforest 他にもあると思うので修正してください。

**Comment by yuforest** [comment]
before_action :set_property, only: %i[show, edit, update, destroy]
このように書くとインスタンスが取得できないエラーが出てしまいます。
もとのコードならうまくいくのですが...
![kyaputya](https://user-images.githubusercontent.com/21303815/40918356-09897636-6841-11e8-9a5a-684ea4de15f6.PNG)

**Comment by norotime** [comment]
@yuforest よくご覧ください。カンマは不要です。
