### ISSUE TITLE
2回インスタンス生成する必要があるのか再考する

### ISSUE THREAD

**Issue by norotime** [yuforest/property-exem#6]
https://github.com/yuforest/property-exem/blob/84074e6e3f7abc868ba937b0f84882662bccb2b1/app/controllers/properties_controller.rb#L13

**Comment by yuforest** [comment]
どうせ追加できるのだから最初から2回作っておかなくてもよいかもしれませんね。
修正しておきます。

**Comment by norotime** [comment]
@yuforest クローズするのは、実装が完了してGitHubにプッシュができたらにしませんか？
