### ISSUE TITLE
HTML拡張子を指定する必要があるのか再考する

### ISSUE THREAD

**Issue by norotime** [yuforest/property-exem#7]
https://github.com/yuforest/property-exem/blob/84074e6e3f7abc868ba937b0f84882662bccb2b1/app/controllers/properties_controller.rb#L41

**Comment by yuforest** [comment]
他の部分は直しましたがここだけこのままでした。
JSONがないのですから指定する必要もありませんよね。
直しておきます。

**Comment by norotime** [comment]
@yuforest コミットメッセージでクローズをお願いします！
https://help.github.com/articles/closing-issues-using-keywords/

**Comment by norotime** [comment]
そうすると、このイシュー上にコミットが紐づいて、辿ってみることができるようになります。

**Comment by yuforest** [comment]
なるほど！
理解しました。

その方法でクローズするようにします。

2018-06-10 16:13 GMT+09:00 Hiroyoshi Noro <notifications@github.com>:
