### ISSUE TITLE
Rubyスタイルガイドに沿って行の文字数制限を設ける

### ISSUE THREAD

**Issue by norotime** [yuforest/property-exem#8]
https://github.com/yuforest/property-exem/blob/84074e6e3f7abc868ba937b0f84882662bccb2b1/app/controllers/properties_controller.rb#L51

https://github.com/fortissimo1997/ruby-style-guide/blob/japanese/README.ja.md#align-multiline-arrays

**Comment by yuforest** [comment]
一行を80文字までに修正しておきます。

**Comment by norotime** [comment]
@yuforest 修正したら、コミットメッセージでクローズする方法でお願いします！
https://help.github.com/articles/closing-issues-using-keywords/
